# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import coordinator_pb2 as coordinator__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in coordinator_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class CoordinatorStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RegisterWorker = channel.unary_unary(
                '/coordinator.Coordinator/RegisterWorker',
                request_serializer=coordinator__pb2.WorkerInfo.SerializeToString,
                response_deserializer=coordinator__pb2.RegisterAck.FromString,
                _registered_method=True)
        self.GetRoutingTable = channel.unary_unary(
                '/coordinator.Coordinator/GetRoutingTable',
                request_serializer=coordinator__pb2.Empty.SerializeToString,
                response_deserializer=coordinator__pb2.RoutingTable.FromString,
                _registered_method=True)
        self.SubscribeRoutingTable = channel.unary_stream(
                '/coordinator.Coordinator/SubscribeRoutingTable',
                request_serializer=coordinator__pb2.Empty.SerializeToString,
                response_deserializer=coordinator__pb2.RoutingTable.FromString,
                _registered_method=True)
        self.UpdateMetrics = channel.unary_unary(
                '/coordinator.Coordinator/UpdateMetrics',
                request_serializer=coordinator__pb2.WorkerMetrics.SerializeToString,
                response_deserializer=coordinator__pb2.Ack.FromString,
                _registered_method=True)


class CoordinatorServicer(object):
    """Missing associated documentation comment in .proto file."""

    def RegisterWorker(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetRoutingTable(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SubscribeRoutingTable(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateMetrics(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CoordinatorServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RegisterWorker': grpc.unary_unary_rpc_method_handler(
                    servicer.RegisterWorker,
                    request_deserializer=coordinator__pb2.WorkerInfo.FromString,
                    response_serializer=coordinator__pb2.RegisterAck.SerializeToString,
            ),
            'GetRoutingTable': grpc.unary_unary_rpc_method_handler(
                    servicer.GetRoutingTable,
                    request_deserializer=coordinator__pb2.Empty.FromString,
                    response_serializer=coordinator__pb2.RoutingTable.SerializeToString,
            ),
            'SubscribeRoutingTable': grpc.unary_stream_rpc_method_handler(
                    servicer.SubscribeRoutingTable,
                    request_deserializer=coordinator__pb2.Empty.FromString,
                    response_serializer=coordinator__pb2.RoutingTable.SerializeToString,
            ),
            'UpdateMetrics': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateMetrics,
                    request_deserializer=coordinator__pb2.WorkerMetrics.FromString,
                    response_serializer=coordinator__pb2.Ack.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'coordinator.Coordinator', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('coordinator.Coordinator', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Coordinator(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def RegisterWorker(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/coordinator.Coordinator/RegisterWorker',
            coordinator__pb2.WorkerInfo.SerializeToString,
            coordinator__pb2.RegisterAck.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetRoutingTable(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/coordinator.Coordinator/GetRoutingTable',
            coordinator__pb2.Empty.SerializeToString,
            coordinator__pb2.RoutingTable.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SubscribeRoutingTable(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/coordinator.Coordinator/SubscribeRoutingTable',
            coordinator__pb2.Empty.SerializeToString,
            coordinator__pb2.RoutingTable.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateMetrics(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/coordinator.Coordinator/UpdateMetrics',
            coordinator__pb2.WorkerMetrics.SerializeToString,
            coordinator__pb2.Ack.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
