# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: coordinator.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'coordinator.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11\x63oordinator.proto\x12\x0b\x63oordinator\"\x8d\x01\n\nWorkerInfo\x12\x0c\n\x04role\x18\x01 \x01(\t\x12\x0c\n\x04rank\x18\x02 \x01(\x05\x12\x0c\n\x04host\x18\x03 \x01(\t\x12\x11\n\tdevice_id\x18\x04 \x01(\x05\x12\x12\n\nworld_size\x18\x05 \x01(\x05\x12\x15\n\rlocal_experts\x18\x06 \x03(\x05\x12\x17\n\x0f\x64\x65\x65pep_endpoint\x18\x07 \x01(\t\"\xa5\x01\n\rWorkerMetrics\x12\x0c\n\x04role\x18\x01 \x01(\t\x12\x0c\n\x04rank\x18\x02 \x01(\x05\x12\x15\n\rqueue_len_avg\x18\x03 \x01(\x01\x12\x19\n\x11\x64ispatch_rate_tps\x18\x04 \x01(\x01\x12\x17\n\x0f\x63\x61\x63he_miss_rate\x18\x05 \x01(\x01\x12\x14\n\x0ctimestamp_us\x18\x06 \x01(\x03\x12\x17\n\x0fper_expert_load\x18\x07 \x03(\x01\"\\\n\x0cRoutingTable\x12\x0f\n\x07version\x18\x01 \x01(\x03\x12\x16\n\x0e\x65xpert_to_rank\x18\x02 \x03(\x05\x12\x0c\n\x04mode\x18\x03 \x01(\t\x12\x15\n\rvalid_from_us\x18\x04 \x01(\x03\"c\n\x0bRegisterAck\x12\x1d\n\x15initial_table_version\x18\x01 \x01(\x03\x12\x16\n\x0e\x61ssigned_group\x18\x02 \x01(\t\x12\x10\n\x08\x61\x63\x63\x65pted\x18\x03 \x01(\x08\x12\x0b\n\x03msg\x18\x04 \x01(\t\"\x07\n\x05\x45mpty\"\x1e\n\x03\x41\x63k\x12\n\n\x02ok\x18\x01 \x01(\x08\x12\x0b\n\x03msg\x18\x02 \x01(\t2\x9d\x02\n\x0b\x43oordinator\x12\x43\n\x0eRegisterWorker\x12\x17.coordinator.WorkerInfo\x1a\x18.coordinator.RegisterAck\x12@\n\x0fGetRoutingTable\x12\x12.coordinator.Empty\x1a\x19.coordinator.RoutingTable\x12H\n\x15SubscribeRoutingTable\x12\x12.coordinator.Empty\x1a\x19.coordinator.RoutingTable0\x01\x12=\n\rUpdateMetrics\x12\x1a.coordinator.WorkerMetrics\x1a\x10.coordinator.Ackb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'coordinator_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_WORKERINFO']._serialized_start=35
  _globals['_WORKERINFO']._serialized_end=176
  _globals['_WORKERMETRICS']._serialized_start=179
  _globals['_WORKERMETRICS']._serialized_end=344
  _globals['_ROUTINGTABLE']._serialized_start=346
  _globals['_ROUTINGTABLE']._serialized_end=438
  _globals['_REGISTERACK']._serialized_start=440
  _globals['_REGISTERACK']._serialized_end=539
  _globals['_EMPTY']._serialized_start=541
  _globals['_EMPTY']._serialized_end=548
  _globals['_ACK']._serialized_start=550
  _globals['_ACK']._serialized_end=580
  _globals['_COORDINATOR']._serialized_start=583
  _globals['_COORDINATOR']._serialized_end=868
# @@protoc_insertion_point(module_scope)
